# Generated by Django 5.2 on 2025-05-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('dateofbirth', models.DateField()),
                ('dateofjoining', models.DateField()),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Jewellery', 'Jewellery'), ('Shopping', 'Shopping')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
