# Generated by Django 5.2 on 2025-05-02 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='budget_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=100, null=True)),
                ('employee_category', models.CharField(max_length=20, null=True)),
                ('budget_amount', models.IntegerField(null=True)),
                ('status_key', models.IntegerField(default=1)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=20, null=True)),
                ('employee_category', models.CharField(max_length=20, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('status_key', models.IntegerField(default=1)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='status_key',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
