# Generated by Django 5.2 on 2025-05-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0002_budget_details_emp_details_employee_status_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_details',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
