# Generated by Django 5.2 on 2025-05-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0003_emp_details_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_details',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='budget_details',
            name='employee_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='employee_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
