# Generated by Django 5.2 on 2025-05-05 11:20
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0004_budget_details_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_details',
            name='Expensed_date',
            field=models.DateField(null=True),
        ),
    ]
