# Generated by Django 5.2 on 2025-05-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0005_emp_details_expensed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_details',
            name='Expensed_date',
        ),
        migrations.AddField(
            model_name='emp_details',
            name='expenses_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
