# Generated by Django 5.2 on 2025-05-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0006_remove_emp_details_expensed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
